"""
yield_model.py - Wheat and Rice Yield Forecasting for KisanAI Advisor
Loads historical Pakistani yield data and runs a Random Forest Regressor.
"""

from typing import Dict, Any, Optional
import os
import pandas as pd
import numpy as np
import joblib
from sklearn.ensemble import RandomForestRegressor

DEFAULT_DATA_PATH = "data/yield_data.csv"
DEFAULT_MODEL_PATH = "models/yield_model.joblib"


def load_yield_data(data_path: str = DEFAULT_DATA_PATH) -> pd.DataFrame:
    """
    Loads historical Pakistani agricultural dataset containing:
    crop, fertilizer_npk_kg_ha, irrigation_rounds, avg_temp_c, rainfall_mm, historical_yield_kg_ha, yield_kg_ha
    """
    if os.path.exists(data_path):
        return pd.read_csv(data_path)

    # Built-in baseline records if CSV is not yet placed
    records = [
        {"crop": "Wheat", "fertilizer_npk_kg_ha": 160, "irrigation_rounds": 5, "avg_temp_c": 21.0, "rainfall_mm": 85, "historical_yield_kg_ha": 3400, "yield_kg_ha": 3450},
        {"crop": "Wheat", "fertilizer_npk_kg_ha": 200, "irrigation_rounds": 6, "avg_temp_c": 20.5, "rainfall_mm": 110, "historical_yield_kg_ha": 3800, "yield_kg_ha": 3850},
        {"crop": "Wheat", "fertilizer_npk_kg_ha": 120, "irrigation_rounds": 4, "avg_temp_c": 23.0, "rainfall_mm": 60, "historical_yield_kg_ha": 2900, "yield_kg_ha": 2950},
        {"crop": "Rice", "fertilizer_npk_kg_ha": 150, "irrigation_rounds": 14, "avg_temp_c": 31.0, "rainfall_mm": 420, "historical_yield_kg_ha": 3200, "yield_kg_ha": 3300},
        {"crop": "Rice", "fertilizer_npk_kg_ha": 180, "irrigation_rounds": 16, "avg_temp_c": 30.5, "rainfall_mm": 480, "historical_yield_kg_ha": 3600, "yield_kg_ha": 3650},
        {"crop": "Rice", "fertilizer_npk_kg_ha": 110, "irrigation_rounds": 12, "avg_temp_c": 32.0, "rainfall_mm": 350, "historical_yield_kg_ha": 2800, "yield_kg_ha": 2750},
    ]
    return pd.DataFrame(records)


def train_and_save_model(data_path: str = DEFAULT_DATA_PATH, model_path: str = DEFAULT_MODEL_PATH):
    """
    Trains a Random Forest Regressor and serializes it to models/yield_model.joblib
    """
    df = load_yield_data(data_path)
    df["is_wheat"] = (df["crop"] == "Wheat").astype(int)

    features = ["is_wheat", "fertilizer_npk_kg_ha", "irrigation_rounds", "avg_temp_c", "rainfall_mm", "historical_yield_kg_ha"]
    X = df[features]
    y = df["yield_kg_ha"]

    model = RandomForestRegressor(n_estimators=100, max_depth=6, random_state=42)
    model.fit(X, y)

    os.makedirs(os.path.dirname(model_path), exist_ok=True)
    joblib.dump(model, model_path)
    return model


def load_yield_model(model_path: str = DEFAULT_MODEL_PATH):
    """
    Loads saved Random Forest model, or trains one if file does not exist.
    """
    if os.path.exists(model_path):
        try:
            return joblib.load(model_path)
        except Exception:
            pass
    return train_and_save_model(DEFAULT_DATA_PATH, model_path)


def predict_crop_yield(
    crop: str,
    area_value: float,
    area_unit: str,
    fertilizer_npk: float,
    irrigation_rounds: int,
    avg_temp: float,
    rainfall: float,
    historical_yield: float,
    model=None
) -> Dict[str, Any]:
    """
    Predicts crop harvest in Tonnes, Maunds, and kg/ha.
    1 maund (من) = 40 kg
    """
    # Convert area to hectares for calculation
    if area_unit.lower() == "acres":
        area_ha = area_value / 2.47105
        area_acres = area_value
    else:
        area_ha = area_value
        area_acres = area_value * 2.47105

    if model is None:
        model = load_yield_model()

    is_wheat = 1 if crop == "Wheat" else 0
    features = np.array([[is_wheat, fertilizer_npk, irrigation_rounds, avg_temp, rainfall, historical_yield]])
    predicted_kg_ha = float(model.predict(features)[0])

    # Safeguard bounds based on Pakistani field averages
    predicted_kg_ha = max(1600.0, min(6500.0, predicted_kg_ha))

    total_kg = predicted_kg_ha * area_ha
    total_tonnes = total_kg / 1000.0
    total_maunds = total_kg / 40.0

    return {
        "crop": crop,
        "area_hectares": round(area_ha, 2),
        "area_acres": round(area_acres, 1),
        "yield_per_hectare_kg": int(round(predicted_kg_ha)),
        "total_yield_kg": int(round(total_kg)),
        "total_yield_tonnes": round(total_tonnes, 2),
        "total_yield_maunds": round(total_maunds, 1),
        "warning": "NOTICE: This forecast is an estimate generated by a scikit-learn Random Forest model. Actual harvest depends on seed quality, timely weed control, and localized weather shocks."
    }
